name: arduino_ctrl
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  flutter_joystick: ^0.2.1
  flex_color_scheme: ^7.3.1
  flutter_native_splash: ^2.3.10
  google_fonts: 6.1.0
  flutter_svg: ^2.0.10
  flutter_utils:
    git:
      url: git@github.com:sisitech/flutter_utils.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  flutter_utils:
    git:
      url: git@github.com:sisitech/flutter_utils.git
      ref: "b68a85f"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - google_fonts/

flutter_native_splash:
  color: "ECECEC"
  color_dark: "000000"
  image: "assets/robo.png"

  android_12:
    image: "assets/robo.png"